'use strict';

const CONSTANTS = {};

CONSTANTS.STRIPE_WEBHOOK_ENDPOINTS = [

];

CONSTANTS.USER_TYPE = {
    ADMIN: 1,
    PARTNER: 2,
    COMPANY: 3,
};

CONSTANTS.SECURITY = {
    BCRYPT_SALT: 8,
};

CONSTANTS.NORMAL_PROJECTION = {
    __v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0, password: 0,
};
CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = ['csv', 'png'];
CONSTANTS.ALLOWED_EXTENSIONS_FOR_PROFILE_IMAGE = ['jpg', 'png', 'jpeg', 'JPG', 'PNG', 'JPEG', 'webp', 'WEBP'];

CONSTANTS.ERROR_TYPES = {
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    MONGO_EXCEPTION: 'MONGO_EXCEPTION',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
};

CONSTANTS.MESSAGES = require('./message');

module.exports = CONSTANTS;