module.exports = {

    //* Generic messages
    SERVER_IS_WORKING_FINE: 'Server is working fine.',
    REGISTERED_SUCCESSFULLY: 'Registered successfully.',
    SEND_VERIFY_EMAIL_TO_USER: 'Email sent to the registered email, please verify email to login miniheart.',
    VERIFY_EMAIL_BEFORE_LOGIN: 'Your email has not been verified yet, please verify your email before login.',
    PLEASE_VERIFY_MOBILE_BEFORE_UPDATE_2FA: 'Please verify mobile before update 2fa security',
    MOBILE_NUMBER_VERIFIED: 'Mobile number verified',
    ALREADY_MOBILE_NUMBER_VERIFIED: 'Mobile number already verified',
    OTP_SENT_TO_NUMBER: 'OTP sent to phone successfully',
    OTP_SENT_TO_EMAIL: 'OTP sent to email successfully',
    OTP_SENT_TO_EMAIL_AND_PHONE: 'OTP sent to email and phone successfully',
    ERROR_WHILE_SENDING_OTP: 'An error occured while sending OTP',
    OTP_ALREADY_SENT: 'OTP already sent',
    DATA_FETCHED_SUCCESSFULLY: 'Data fetched successfully',
    WEBHOOK_RECIEVED: 'Webhook event received',
    OTP_SENT_TO_YOUR_EMAIL: 'OTP has been sent to your registered email address.',
    EMAIL_VERIFIED: 'Email verified successfully.',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    SOMETHING_WENT_WRONG_TRY_AGAIN: 'Something went wrong, please try again in some time.',
    INTERNAL_SERVER_ERROR: 'Internal server error!',
    UNAUTHORIZED: 'Unauthorized access!',
    FORBIDDEN: 'Unrestricted access!',
    LOGGED_IN_SUCCESSFULLY: 'Logged in successfully.',
    EMAIL_ALREADY_EXISTS: 'Email already exists.',
    INVALID_EMAIL: 'Invalid email address.',
    INVALID_PASSWORD: 'Invalid password.',
    SAME_CURRENT_AND_OLD_PASSWORD: 'Current password and old password cannot be same.',
    SAME_CURRENT_AND_OLD_EMAIL: 'Current email and new email cannot be same',
    NOT_FOUND: 'Data not found.',
    COULD_NOT_UPDATE_PRICE: 'Could not update price.',
    INCONSISTENT_DATA: 'Lands, zones or co-ordinates count doesn\'t match',
    ACCOUNT_NOT_ACTIVE: 'This account is not active anymore',
    LOGGED_OUT_SUCCESSFULLY: 'Logged out successfully.',
    PROFILE_UPDATE_SUCCESSFULLY: 'Profile updated successfully.',
    SUCCESS: 'Success.',
    FILE_REQUIRED_IN_PAYLOAD: 'File required in payload.',
    FILE_UPLOADED_SUCCESSFULLY: 'File uploaded successfully.',
    NUMBER_NOT_EXIST: 'Given mobile number is not registered.',
    NUMBER_ALREADY_EXIST: 'This number has been already registerd.',
    OTP_EXPIRED: 'Your OTP has expired.',
    OTP_INVALID: 'Your OTP is invalid.',
    INVALID_ETHEREUM_ADDRESS: 'publicAddress must be a valid ethereum addresses.',
    FORGOT_PASSWORD_EMAIL_SENT_SUCCESSFULLY: 'Forget password email sent successfully',
    SOCKET: {
        USER_CONNECTED_SUCCESSFULLY: 'Users Connected successfully',
        USER_DISCONNECT: 'User disconnected',
        SOCKET_IS_RUNNING_FINE: 'Socket is running fine',
        MESSAGE_SENT: 'Message sent successfully',
        MESSAGE_READ: 'Message read updated Successfully',
    },
    MISSING_DATA: 'Missing data in payload',
    LIST_FETCHED_SUCCESSFULLY: 'List fetched successfully.',
    PASSWORD_UPDATED_SUCCESSFULLY: 'Password updated successfully.',
    INVALID_TOKEN: 'Token must be valid',
    TOKENS_CLAIMED_SUCCESSFULLY: 'Tokens claimed successfully',
    PASSWORD_DOESNT_MATCH: 'Password doesn\'t match',
    NOTIFICATION_SETTINGS_UPDATED: 'Notification settings updated successfully',
    ERROR_WHILE_SENDING_FORGOT_PASSWORD_EMAIL: 'Error while sending forgot password email',
    CURRENT_PASSWORD_DOESNT_MATCH: 'Current password is incorrect',
    ERROR_WHILE_CREATING_ACCOUNT: 'Error while creating account, please try again later',
    INVITATION_SENT_SUCCESSFULLY: 'Invitaion sent successfully',
    DONATION_AMOUNT_LESS_THAN_MIN_VALUE: 'Minimum donation criteria doesn\'t match',
    LOW_BALANCE_AMOUNT: 'Insufficient balance',
    EMAIL_ALREADY_VERIFIED: 'Email already verified',
    EMAIL_VERIFICATION_SESSION_NOT_FOUND: 'Email verification session not found',
    ERROR_WHILE_SENDING_INVITATION_EMAIL: 'Error while sending invitation email',
    EMAIL_CAN_BE_USED: 'Email can be used',
    PLEASE_VERIFY_EMAIL: 'Please verify your email before this operation',
    EMAIL_SENT_SUCCESSFULLY: 'Email sent successfully',
    ERROR_WHILE_SENDING_VERIFICATION_EMAIL: 'Error while sending verification email.',
    ERROR_WHILE_LOGIN: 'Error while login',
    PHONE_ALREADY_EXISTS: 'Phone number already associated with an account',
    PHONE_CAN_BE_USED: 'Phone number can be used',
    ONLY_ONE_KEY_IS_ACCEPTED: 'Only one key is accepted',
    ADMIN_CREATED_SUCCESSFULLY: 'Admin created successfully',
    ADMIN_UPDATED_SUCCESSFULLY: 'Admin updated successfully',
    PROFILE_PIC_UPDATED: 'Profile image updated successfully',
    SUPER_ADMIN_UPDATED_SUCCESSFULLY: 'Super Admin updated successfully',
    ADMIN_ALREADY_EXISTS: 'Admin email already exists',
    ADMIN_DELETED_SUCCESSFULLY: 'Admin deleted successfully',
    ADMIN_LIST_FETCHD_SUCCESSFULLY: 'Admin list fetched successfully',
    ADMIN_ACTION_LIST_SUCCESSFULLY: 'Admin action list fetched successfully',
    PASSWORD_UPDATE_SUCCESSFULLY: 'Your Password updated successfully',
    //* Maintenance messages
    MAINTENANCE_MODE_ON: 'Maintenance mode is on now',
    MAINTENANCE_MODE_OFF: 'Maintenance mode is off now',

    //* Users messages
    ERROR_WHILE_DELETING_ACCOUNT: 'Error while deleting account, please try again later',
    USER_ALREADY_EXISTS: 'An account with this email address already exists.',
    NO_USER_FOUND_WITH_THIS_EMAIL: 'This email address is not associated with any existing account.',
    NO_USER_FOUND: 'User not found.',
    USER_UPDATED_SUCCESSFULLY: 'User updated successfully.',
    USER_ACTIVATED: 'User have been activated.',
    USER_DEACTIVATED: 'User have been deactivated.',
    INVALID_USER: 'Invalid email or password.',
    USER_INACTIVE: 'Your account is currently inactive by admin',
    USERS_CREATED_SUCCESSFULLY: 'User\'s created successfully',
    USER_NOT_FOUND: 'User not found',
    PARTNER_NOT_FOUND: 'partner not found',
    PROFILE_FETCHED_SUCCESSFULLY: 'User\'s profile fetched successfully',
    USER_DELETED_SUCCESSFULLY: 'User deleted successfully',
    USERS_FETCHED: 'Users fetched successfully',
    USERS_INDIVIDUALS_FETCHED_SUCCESSFULLY: 'User\'s individuals fetched successfully',
    USERS_MEMBERS_FETCHED_SUCCESSFULLY: 'User\'s members fetched successfully',
    USER_ACCESS_UPDATED_SUCCESSFULLY: 'User access updated successfully',
    USER_SUBSCRIBED_FOR_DONATION: 'User subscribed for donation successfully',
    COMPANIES_FETCHED_SUCCESSFULLY: 'Companies fetched successfully',
    ERROR_WHILE_SUBSCRIBING_USER: 'Error while subscribing to user',
    ALREADY_SUBSCRIBED_TO_USER: 'Already subscribed to user',
    MEMBERS_ACTIVITY_FETCHED: 'Members activity fetched successfully',
    MEMBERS_FETCHED_SUCCESSFULLY: 'Members fetched successfully',
    PARTNERS_FETCHED_SUCCESSFULLY: 'Partner\'s fetched successfully',
    USERS_GROUPING_FETCHED_SUCCESSFULLY: 'Users grouping fetched successfully',
    PARTNER_CANNOT_SUBSCRIBE_TO_ANYONE: 'Partner cannot subscribe to anyone',
    USER_ENABLED_2FA: '2FA for user enabled successfully',
    ALREADY_USER_ENABLED_2FA: '2FA for user already enabled ',
    ALREADY_USER_DISABLED_2FA: '2FA for user already disabled ',
    USER_DISABLED_2FA: '2FA for user disabled successfully',
    USER_WALLET_INFO_FETCHED: 'User cash wallet info fetched successfully',
    ADMIN_BALANCE_FETCHED: 'Admin balance fetched successfully',

    //* Association messages
    USERS_ASSOCIATIONS_FETCHED_SUCCESSFULLY: 'User\'s associations fetched successfully',
    ASSOCIATIONS_FETCHED_SUCCESSFULLY: 'Associations fetched successfully',

    //* Subscription messages
    SUBSCRIPTION_CANCELLED_SUCCESSFULLY: 'Subscription cancelled successfully',
    SUBSCRIPTION_CREATED_SUCCESSFULLY: 'Subscription created successfully',
    SUBSCRIPTION_UPDATED_SUCCESSFULLY: 'Subscription updated successfully',
    SUBSCRIPTION_WEBHOOK_RECIEVED: 'Subscription webhook received',
    ERROR_WHILE_CANCELLING_SUBSCRIPTION: 'Error while cancelling subscription',
    ERROR_WHILE_CREATING_SUBSCRIPTION: 'Error while creating subscription',
    ERROR_WHILE_UPDATING_SUBSCRIPTION: 'Error while updating subscription',
    SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
    SUBSCRIPTIONS_FETCHED_SUCCESSFULLY: 'Subscriptions fetched successfully',
    SUBSCRIPTION_FETCHED_SUCCESSFULLY: 'Subscription fetched successfully',
    SUBSCRIPTION_ALREADY_EXISTS: 'Subscription already exists',
    PAYMENT_SECRET_GENERATED: 'Payment secret generated successfully',
    ERROR_WHILE_GENERATING_PAYMENT_SECRET: 'Error while generated payment secret',
    ERROR_WHILE_DONATING_TO_ADMIN: 'Error while donating to Mini Hearts',

    //* Stripe messages
    STRIPE_COUNTRY_NOT_SUPPORTED: 'Your country is currently not supported by our payment processing provider',
    STRIPE_ADDRESS_NOT_SUPPORTED: 'The country of the account address provided does not match the country of the account',
    STRIPE_CARD_EXPIRED: 'Your card is expired, please try with another card',
    STRIPE_CARD_DECLINED: 'Your card is declined by our payment processing partner, please try with another card',
    STRIPE_CARD_INCORRECT_CVC: 'Your card is declined due to an incorrect CVC, please try again with the correct CVC',
    STRIPE_CARD_INCORRECT_CARD_NUMBER: 'Your card is declined due to an incorrect number, please try with correct number',
    STRIPE_CARD_PROCESSING_ERROR: 'Card processing error by our payment processing partner, please try with another card',
    STRIPE_CARD_WRONG_DATES: 'Your card is declined due to an invalid expiration date, please try with correct date',
    STRIPE_INVALID_NUMBER: 'Error while creating connect account due to invalid phone number',

    CARD_UPDATED_SUCCESSFULLY: 'Card updated successfully',
    CARD_ADDED_SUCCESSFULLY: 'Card added successfully',
    CARD_DELETED_SUCCESSFULLY: 'Card deleted successfully',
    NO_STRIPE_ACCOUNT_DATA_FOUND: 'No stripe data found',
    ERROR_WHILE_ADDING_CARD: 'Error while adding card',
    ERROR_WHILE_UPDATING_CARD: 'Error while updating card',
    ERROR_WHILE_DELETING_CARD: 'Error while deleting card',
    ERROR_WHILE_FETCHING_CARD: 'Error while fetching cards',
    STRIPE_ACCOUNT_LINK_CREATED: 'Stripe account link created',
    STRIPE_CONNECT_ACCOUNT_ACTIVE: 'Stripe connect account active',
    STRIPE_CONNECT_ACCOUNT_CREATED: 'Stripe connect account created',
    ERROR_CREATING_STRIPE_CONNECT_ACCOUNT: 'Error while creating stripe connect account, please try again later',
    WITHDRAWL_INITIATED: 'Withdrawl process has been initiated successfully',
    CANT_WITHDRAW_AMOUNT: 'Cannot withdraw amount at the moment, try again later',
    PAYMENT_INTENT_WEBHOOK_RECIEVED: 'Payment intent webhook received',
    INVOICE__WEBHOOK_RECEIVED: 'Invoice event received',
    BANK_UPDATED_SUCCESSFULLY: 'Bank updated successfully',
    BANK_MARKED_DEFAULT_SUCCESSFULLY: 'Bank marked default successfully',
    STRIPE_ACCOUNT_LINK_ERROR: 'Error while creating stripe connect onboarding link',
    WITHDRAWL_ERROR: 'There was an error during the withdrawal process. Please try again later',
    BANK_FETCHED_SUCCESSFULLY: 'Banks fetched successfully',
    BANK_DELETED_SUCCESSFULLY: 'Bank deleted successfully',
    STRIPE_DATA_UPDATE_ERROR: 'Error while updating payment processing provider data',
    STRIPE_CONNECT_ACCOUNT_NOT_ACTIVE: 'Stripe connect account not active, please update it for further operations',
    BANK_ACCOUNT_MISSING_STRIPE: 'Bank account information missing',
    NO_CARD_PRESENT: 'Card missing for payment',
    DEFAULT_CARD_NOT_SET: 'Please set a card as your default card',
    NO_BALANCE_TO_WITHDRAW: 'No balance to withdraw',
    DONATION_COMPLETED: 'Donation completed',
    DONATION_FAILED: 'Donation failed',
    CANNOT_DELETE_DEFAULT_BANK_ACCOUNT: 'Cannot delete default bank account. Please change default bank account first',
    STRIPE_CONNECT_ACCOUNT_ACTIVE_ADD_BANK: 'Connect account active, add bank account to proceed',
    TRANSFER_WEBHOOK_RECIEVED: 'Transfer webhook recieved',
    PAYOUT_WEBHOOK_RECIEVED: 'Payout webhook recieved',
    PLEASE_TRY_AGAIN_AFTER_7_DAYS: 'Referral bonus is being processed, try again in 7-8 working days.',
    DONATION_SUCCESSFULL: 'Donation successfull',
    CANNOT_WITHDRAW_MONEY_IF_FUNDRAISER_STORY_BLOCK: 'Can\'t withdraw amount as your story is blocked',
    CANNOT_SUBSCRIBE_TO_YOURSELF: 'Cannot self subscribe',
    CANNOT_SUBSCRIBE_AS_OTHER_USER_ALREADY_SUBSCRIBED_YOU: 'Cannot subscribe as other user already subscribed you',
    CARD_ALREADY_ADDED: 'Card already added',

    //* Referral messages
    REFERRAL_CODE_DOES_NOT_EXISTS: 'The code does not exist',
    REFERRAL_CODE_CREATED_SUCCESSFULLY: 'Referral code created successfully',
    REFERRAL_CODE_USER_DOES_NOT_EXISTS: 'Referral code user doesn\'t exists',
    REFERRAL_CODE_UPDATED_SUCCESSFULLY: 'Referral code updated successfully',
    INVALID_REFERRAL_CODE: 'Invalid referral code',
    REFERRAL_TEMPLATE_GENERATED: 'Referral template generated successfully',
    REFERRAL_CODE_DELETED_SUCCESSFULLY: 'Referral code deleted successfully',
    REFERRAL_CODES_FETCHED_SUCCESSFULLY: 'Referral codes fetched successfully',
    REFERRAL_CODE_ALREADY_USED: 'Cannot delete referral code as it\'s already used by users',
    REFERRAL_BONUSES_FETCHED_SUCCESSFULLY: 'Referral Bonuses list fetched sucessfully',
    REFERRAL_CODE_FETCHED_SUCCESSFULLY: 'Referral code fetched successfully',
    REFERRAL_CODE_EXISTS: 'Referral code exists',
    REFERAL_CODE_EXPIRE: 'Referral Code expired',
    REFERAL_CODE_USED_BY_USER: 'You cannot use code more than one time',
    INVALID_REFERRAL_CODE_FORMAT: 'Invalid referral code format',
    DEFAULT_REFERRAL_CODE_CANNOT_BE_DELETED: 'Default referral code cannot be deleted',
    REFERRAL_CODE_CAN_BE_USED_BY_PARTNER: 'This referral code can only be used as partner',
    REFERRAL_CODE_ALLOW_FOR_USER: 'Valid User for Bonus Code',

    //* Listing messages
    LISTING_REVIEW_ADDED_SUCCESSFULLY: 'Listing review added successfully',
    LISTING_COUPON_ADDED_SUCCESSFULLY: 'Listing coupon added successfully',
    LISTING_ADDED_SUCCESSFULLY: 'Listing added successfully',
    LISTINGS_FETCHED_SUCCESSFULLY: 'Listings fetched successfully',
    LISTING_FETCHED_SUCCESSFULLY: 'Listing fetched successfully',
    PRICE_ADDED_SUCCESSFULLY: 'Price added successfully',

    //* Listing messages
    STORY_REVIEW_ADDED_SUCCESSFULLY: 'Story review added successfully',
    STORY_COUPON_ADDED_SUCCESSFULLY: 'Story coupon added successfully',
    STORY_ADDED_SUCCESSFULLY: 'Story added successfully',
    FOUNDATION_ADDED_SUCCESSFULLY: 'Foundation added successfully',
    PARTNER_ADDED_SUCCESSFULLY: 'Partner added successfully',
    BLOCK_STORYS_FETCHED_SUCCESSFULLY: 'block stories fetched successfully',
    STORYS_FETCHED_SUCCESSFULLY: 'Stories fetched successfully',
    STORY_FETCHED_SUCCESSFULLY: 'Story fetched successfully',
    STORY_UPDATE_SUCCESSFULLY: 'Story updated successfully.',
    STORY_DELETED_SUCCESSFULLY: 'Story deleted successfully',
    STORY_NOT_FOUND: 'Story not found',
    CANNOT_DONATE_ON_INACTIVE_STORY: 'This fundraiser is not accepting funds anymore',
    UPDATE_STORY_NOT_FOUND: 'update story not found',
    STORY_IS_DELETED: 'Story is deleted',
    STORY_IS_BLOCKED: 'Story is blocked',
    STORY_REPORTED_SUCCESSFULLY: 'Stroy Reported successfully',
    REPORT_STORY_FETCH_SUCCESSFULLY: 'Report Story fetch successfully',
    REPORT_CATEGORY_SUCCESSFULLY: 'Report Category fetch successfully',
    STORY_UNAUTHORIZED_OPERATION: 'Unauthorized operation.',
    STORY_CATEGORIES_INVALID: 'Invalid story categories.',
    STORY_CANNOT_RECEIVE_DONATION: 'Not able to receive donation at this moment.',
    STORY_MINIMUM_MINIHEART_DONATION_NOT_FULFILLED: 'Minimum mini-heart donation not fulfilled',
    STORY_MONTHLY_ACTIVITY: 'monthly data activity fetched successfully',
    COMMENT_DELETE_SUCCESSFULLY: 'Comment deleted successfully',
    COMMENT_ADDED_SUCCESSFULLY: 'Comment added successfully',

    //* Report messages
    REPORT_GENERATED_SUCCESSFULLY: 'Report generated successfully',
    REPORT_LINK_GENERATED_SUCCESSFULLY: 'Report link generated successfully',
    NO_REPORTS_TO_GENERATE: 'No reports to generate',
    TRANSACTION_GRAPH_GENERATED_SUCCESSFULLY: 'Transaction graph generated successfully',
    USER_EARNING_GRAPH_GENERATED_SUCCESSFULLY: 'User\'s earning graph generated successfully',
    GRAPH_DATA_GENERATED_SUCCESSFULLY: 'Graph data generated successfully',
    STATEMENTS_GENERATED_SUCCESSFULLY: 'User statements generated successfully',
    TOP_DONORS_FETCHED_SUCCESSFULLY: 'Top donors fetched successfully',
    TOP_DONATIONS_BY_COUNTRY_FETCHED_SUCCESSFULLY: 'Top donation by country fetched successfully',
    DAILY_CUSTOMERS_GRAPH_GENERATED_SUCCESSFULLY: 'Daily customers graph generated successfully',
    CSV_GENERATED_SUCCESSFULLY: 'CSV generated successfully',
    CSV_NOT_GENERATED: 'CSV not generated',
    CUSTOMERS_AVERAGE_COUNT_FETCHED: 'Customers average count fetched successfully',

    //* Advertisement messages
    ADVERTISEMENT_ADDED_SUCCESSFULLY: 'Advertisement added successfully',
    ADVERTISEMENT_DELETED_SUCCESSFULLY: 'Advertisement deleted successfully',
    ADVERTISEMENT_NOT_FOUND: 'Advertisement not found',
    ADVERTISEMENT_UPDATED_SUCCESSFULLY: 'Advertisement updated successfully',

    //* Transaction messages
    TRANSACTION_FETCHED_SUCCESSFULLY: 'Transaction fetched successfully',
    TRANSACTION_NOT_FOUND: 'Transaction not found',

    //* Constant messages
    MINIMUM_DONATION_AMOUNT_SET: 'Minimum donation amount set successfully',
    CONSTANTS_NOT_FOUND: 'No constants found',
    CONSTANTS_UPDATED_SUCCESSFULLY: 'Constants updated successfully',
    PAYMENT_INTENT_CREATED: 'Payment intent created',
    USERID_REQUIRED: 'User Id required',
    RAFFLE_TICKET_INFO_CREATED_SUCCESSFULLY: 'Raffle Ticket info created successfully',
    RAFFLE_TICKET_INFO_FETCHED_SUCCESSFULLY: 'Raffle Ticket info fetched successfully',
    RAFFLE_TICKET_INFO_UPDATED_SUCCESSFULLY: 'Raffle Ticket info updated successfully',
    RAFFLE_TICKET_INFO_DELETED_SUCCESSFULLY: 'Raffle Ticket info deleted successfully',

    // Contact Fundraiser message
    MESSAGE_CREATED_SUCCESSFULLY: 'Message Sent successfully.',

    // Story message
    ALREADY_BLOCK: 'Story already blocked',
    ALREADY_UNBLOCK: 'Story already active',

    // Foundation message
    FOUNDATION_FETCHED_SUCCESSFULLY: 'Foundation fetched successfully',
    FOUNDATION_NOT_FOUND: 'Foundation not found',
    FOUNDATION_UPDATED_SUCCESSFULLY: 'Foundation updated successfully',
    FOUNDATION_UPDATION_ERROR: 'Error while updating foundation',
    FOUNDATION_DELETED_SUCCESSFULLY: 'Foundation deleted successfully',
    DONATED_TO_FOUNDATION_SUCCESSFULLY: 'Donated to foundation successfully',
    ERROR_WHILE_DONATING_TO_FOUNDATION: 'Error while donating to the foundation, please try agian later',
    FOUNDATION_STRIPE_NOT_ACTIVE: 'The payment processor account linked to this foundation is currently inactive.',
    FORECASTING_ALREADY_AVAILABLE: 'Forecasting already available',
    FORECASTING_CREATED_SUCCESSFULLY: 'Forecasting created successfully.',
    FORECASTING_UPDATED_SUCCESSFULLY: 'Forecasting updated successfully.',
    FORECASTING_DELETED_SUCCESSFULLY: 'Forecasting deleted successfully',
    FORECASTING_NOT_FOUND: 'Forecasting not found',
    FORECASTING_FETCHED_SUCCESSFULLY: 'Forecasting fetched successfully',
    REVENUE_FOR_MONTH_FETCHED_SUCCESSFULLY: 'Revenue for the month ftched successfully',

    // RaffelTIckets Message
    REFFEAL_TICKETS_MAX_AMOUNT: 'Max amount field is greater than Min amount',
    REFFEAL_TICKET_MIN_AMOUNT: 'Min amount is not equal to last Max Amount',
    MESSAGE_ALREADY_EXISTS: 'Message already exists',
    SUCCESSFULLY_CONTACT_US: 'Thank you for reaching out to us',
    DELETE_DATABASE: 'Successfully delete Database',

    EMAIL_SENT_TO_ADMIN: 'Successfully send email to admin',
    // ChildPost Message
    ADD_CHILD_POST: 'childPost created successfully',
    UPDATE_CHILD_POST: 'childPost updated successfully',
    DELETE_CHILD_POST: 'childPost deleted successfully',
    LIST_CHILD_POST: 'childPost fetch successfully',
    CHILD_POST_NOT_FOUND: 'Child post not found',

    STORY_MIN_DONATION_AMOUNT_PERCENTAGE_ERROR: 'Minimum amount percentage should be greater than or equal to 10%',
    EMAIL_NOT_VERIFIED: 'Email not verified',
    USER_ROLLBACKED: 'User rollbacked successfully',
    CANNOT_DELETE_USER: 'Cannot delete this user',
    PAYMENT_FAILED: 'Please settle your outstanding payments before requesting a withdrawal.',
    PENDING_AMOUNT_IN_BALANCE: 'You have some balance pending for processing, please try again later',

    ACCOUNT_INACTIVE: 'Your account has been temporarily disabled by Mini Hearts management. Please make contact with us via our Chat Now service to discuss your account.',
    BALANCE_WEBHOOK_RECEIVED: 'Balance webhook received',
    WITH_THIS_EMAIL_USER_US_AVAILABLE: 'with this email user is available',
};
